### ISSUE TITLE
what's the performance of SGPA using pointnet rather than pointnet++？

### ISSUE THREAD

**Issue by Bingo-1996** [leo94-hk/SGPA#1]
Hi, author. Thank you for releasing such a wonderful work! 

I have a question about "the performance of the model when replacing PointNet + + in SGPA with PointNet? Because SPD adopts PointNet instead of PointNet++." It seems that there are no ablation results for this change.

**Comment by leo94-hk** [comment]
> Hi, author. Thank you for releasing such a wonderful work!
> 
> I have a question about "the performance of the model when replacing PointNet + + in SGPA with PointNet? Because SPD adopts PointNet instead of PointNet++." It seems that there are no ablation results for this change.

**Comment by leo94-hk** [comment]
@Bingo-1996 Hi, thanks for your interest in our work. 

If we directly apply our proposed prior adaptation module to SPD, the performance also gets significant improvement w.r.t. all metrics on two datasets. You can refer to the supplementary for detailed results. Since our proposed prior adaptation module is based on the geometry feature of point clouds, we therefore use PointNet++ as the point feature extractor, which provides more representative features for more effective prior adaptation and leads to a higher pose accuracy.

**Comment by Bingo-1996** [comment]
Got it! Thank you! The idea of prior adaptation is really wonderful!
